from __future__ import annotations

import argparse
from pathlib import Path

from opencc import OpenCC

HEADER = """# Auto-generated by tools/generate_tigress_simp_charset.py
# Source: core2022.dict.yaml
# Purpose: simplified whitelist for tigress candidate filtering
#
# This file is used only as a reverse-db source for Lua filtering.

---
name: tigress_simp_charset
version: "2026.03.21"
sort: original
use_preset_vocabulary: false
...
"""


def iter_core2022_chars(path: Path):
    started = False
    with path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\n")
            if not started:
                if line.strip() == "...":
                    started = True
                continue
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if not parts:
                continue
            text = parts[0].strip()
            if len(text) != 1:
                continue
            yield text


def build_simplified_charset(chars):
    cc = OpenCC("t2s")
    seen = set()
    ordered = []

    for ch in chars:
        simp = cc.convert(ch)
        if len(simp) != 1:
            continue
        try:
            simp.encode("gb2312")
        except UnicodeEncodeError:
            continue
        if simp in seen:
            continue
        seen.add(simp)
        ordered.append(simp)

    return ordered


def write_dict(path: Path, chars):
    with path.open("w", encoding="utf-8", newline="\n") as f:
        f.write(HEADER)
        for ch in chars:
            f.write(f"{ch}\tt\n")


def main():
    parser = argparse.ArgumentParser(
        description="Generate simplified whitelist charset dictionary for tigress."
    )
    parser.add_argument(
        "--source",
        default="core2022.dict.yaml",
        help="Path to source whitelist dictionary.",
    )
    parser.add_argument(
        "--output",
        default="tigress_simp_charset.dict.yaml",
        help="Path to generated simplified whitelist dictionary.",
    )
    args = parser.parse_args()

    source = Path(args.source)
    output = Path(args.output)

    chars = build_simplified_charset(iter_core2022_chars(source))
    write_dict(output, chars)

    print(f"source: {source}")
    print(f"output: {output}")
    print(f"chars: {len(chars)}")


if __name__ == "__main__":
    main()
